import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/walletcards">WalletCards</Link>
        </li>
        <li>
          <Link to="/notifications">Notifications</Link>
        </li>
        <li>
          <Link to="/dashboard">Dashboard</Link>
        </li>
        <li>
          <Link to="/popupsdashboard">PopupsDashboard</Link>
        </li>
        <li>
          <Link to="/sendpayments">SendPayments</Link>
        </li>
        <li>
          <Link to="/requestpayments">RequestPayments</Link>
        </li>
        <li>
          <Link to="/transactions">Transactions</Link>
        </li>
        <li>
          <Link to="/transactionsfilters">Transactionsfilters</Link>
        </li>
        <li>
          <Link to="/colors">Colors</Link>
        </li>
        <li>
          <Link to="/requestpayments1">RequestPayments1</Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
